model:
  name: 
run:
  verbose: True
  simulate: True
  train: True
  sample: True
  doppel: True
data:
  store_name: doppel_store
  store_size: 10_000
  chunk_size: 500
training:
  trainer_dir: doppel_training
  train_fraction: 0.85
  train_batch_size: 512
  val_batch_size: 512
  num_workers: 0
  device: mps
  n_devices: 1
  min_epochs: 1
  max_epochs: 100
  early_stopping_patience: 7
  learning_rate: 7.e-7
  lr_scheduler_factor: 0.1
  lr_scheduler_patience: 3
  logger:
    type: wandb
    name: default
    project: doppel
    entity: user-name
    offline: False
    log_model: all
    save_dir: doppel_training
sampling:
  n_samples: 10_000
  save_dir: doppel_sample
doppel:
  num_bins: 40
  interpolation: linear
  plot: True
  plot_dir: doppel_sample
compression:
  use_compression: False
  num_features: 1